apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collab
  name: collab
  namespace: collab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: collab
    spec:
      containers:
      - image: gcr.io/jachaela-recipe-book/collab:7
        imagePullPolicy: IfNotPresent
        name: collab
        env:
          - name: PORT
            value: "8080"
        ports:
          - containerPort: 8080
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: collab
spec:
  selector:
    app: collab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
